[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=34.69.25.186
external_signaling_address=34.69.25.186

[neox]
type=endpoint
transport=transport-udp
context=ai-routing
disallow=all
allow=ulaw
aors=neox
identify_by=ip
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[neox_identify]
type=identify
endpoint=neox
match=113.193.111.116

[neox]
type=aor
contact=sip:113.193.111.116:5060

[microsip]
type=endpoint
transport=transport-udp
context=ai-routing
disallow=all
allow=ulaw
auth=microsip_auth
aors=microsip
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[microsip_auth]
type=auth
auth_type=userpass
password=secretpassword
username=aarit

[microsip]
type=aor
max_contacts=1
