[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:15060
external_media_address=34.55.229.163
external_signaling_address=34.55.229.163
local_net=10.0.0.0/8
local_net=172.16.0.0/12
local_net=192.168.0.0/16
local_net=127.0.0.0/8

[neox]
type=endpoint
transport=transport-udp
context=ai-routing
disallow=all
allow=ulaw
aors=neox
identify_by=ip
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[neox_identify]
type=identify
endpoint=neox
match=1.7.93.131

[neox]
type=aor
contact=sip:1.7.93.131:5060

[microsip]
type=endpoint
transport=transport-udp
context=ai-routing
disallow=all
allow=ulaw
auth=microsip_auth
aors=microsip
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[microsip_auth]
type=auth
auth_type=userpass
password=secretpassword
username=aarit

[microsip]
type=aor
max_contacts=1
